name: Compilar OLS Genérico

on:
  workflow_dispatch:

jobs:
  build:
    name: Compilar para ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ols-linux
            build_cmd: |
              sed -i 's/-microarch:[^ ]*/-microarch:generic/g' build.sh
              ./build.sh

    steps:
    - name: Clonar OLS
      uses: actions/checkout@v4
      with:
        repository: 'DanielGavin/ols'

    # Instala la última versión estable de Odin
    - name: Instalar Odin
      uses: laytan/setup-odin@v2
      with:
        odin-version: 'latest'

    - name: Compilar binario
      run: ${{ matrix.build_cmd }}

    - name: Subir Binario Terminado
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ols
